//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetGetApp.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetGetApp.lang.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument list:{0}-h - Displays this help message{0}-url - URL which will be downloaded{0}-o - Name of the output file in which the downloaded content will be saved{0}-r - Repeat download every n seconds (ex.: -r 30){0}-rn Add ascending numbers to the output files as they are created.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue....
        /// </summary>
        internal static string mainAnyKey {
            get {
                return ResourceManager.GetString("mainAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL parameter must be specified (ex.: -url http://google.com).
        /// </summary>
        internal static string mainNoUrl {
            get {
                return ResourceManager.GetString("mainNoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All done, going to sleep for {0} seconds, before the next loop..
        /// </summary>
        internal static string mainSleep {
            get {
                return ResourceManager.GetString("mainSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}....
        /// </summary>
        internal static string urlConnecting {
            get {
                return ResourceManager.GetString("urlConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed.{0}Downloaded content was saved into: .
        /// </summary>
        internal static string urlDone {
            get {
                return ResourceManager.GetString("urlDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed.{0}No output file was specified (or the name was incorrect), downloaded URL content was therefore discarded..
        /// </summary>
        internal static string urlDoneNoFile {
            get {
                return ResourceManager.GetString("urlDoneNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied URL is malformed, or cannot be accessed, I cannot continue..
        /// </summary>
        internal static string urlMalformed {
            get {
                return ResourceManager.GetString("urlMalformed", resourceCulture);
            }
        }
    }
}
